# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0038_post_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
    ]
