# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:27
from __future__ import unicode_literals

from django.db import migrations
import djangocms_blog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0040_auto_20171002_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=djangocms_blog.fields.AutoSlugField(blank=True, db_index=False, max_length=255, verbose_name='slug'),
        ),
    ]
