# Generated by Django 2.1.9 on 2019-06-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0036_auto_20180913_1809'),
        ('djangocms_blog', '0042_mostreadplugin'),
    ]

    operations = [
    ]
