# Generated by Django 2.2.24 on 2021-10-01 10:18

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_blog', '0046_auto_20210112_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_mobile_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djangocms_blog_post_mobile_image', to=settings.FILER_IMAGE_MODEL, verbose_name='main mobile image'),
        ),
    ]
